package financialtracker;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.BorderLayout;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.EventQueue;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;

/**
 *
 * @author shubh
 */
public class Expenses extends javax.swing.JInternalFrame {
    NumberFormat fmt = NumberFormat.getCurrencyInstance();
    NumberFormat per = NumberFormat.getPercentInstance();
    ExpenseCalculator tmp = new ExpenseCalculator ();
    /**
     * Creates new form Purchases
     */
    
    
    public Expenses() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
        
        
        
         
    }

      



      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Groceries = new javax.swing.JTextField();
        MonthlyLabel = new javax.swing.JLabel();
        Gas = new javax.swing.JTextField();
        MedicalLabel = new javax.swing.JLabel();
        Electricity = new javax.swing.JTextField();
        TaxLabel = new javax.swing.JLabel();
        Entertainment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ShowGraph = new javax.swing.JButton();
        MonthlyLabel1 = new javax.swing.JLabel();
        MedicalLabel1 = new javax.swing.JLabel();
        Consumer = new javax.swing.JTextField();
        MedicalLabel2 = new javax.swing.JLabel();
        OtherExpenses = new javax.swing.JTextField();
        MedicalLabel3 = new javax.swing.JLabel();
        Medical = new javax.swing.JTextField();
        MedicalLabel4 = new javax.swing.JLabel();
        Tax = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(660, 450));

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 450));

        Groceries.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Groceries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroceriesActionPerformed(evt);
            }
        });

        MonthlyLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MonthlyLabel.setForeground(new java.awt.Color(255, 255, 255));
        MonthlyLabel.setText("Monthly Gas Bills:");

        Gas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MedicalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicalLabel.setForeground(new java.awt.Color(255, 255, 255));
        MedicalLabel.setText("Electricity Bills:");

        Electricity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        TaxLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TaxLabel.setForeground(new java.awt.Color(255, 255, 255));
        TaxLabel.setText("Monthly Entertainment:");

        Entertainment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Entertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertainmentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Expense:");

        TotalTxt.setEditable(false);
        TotalTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        CalculateButton.setBackground(new java.awt.Color(47, 70, 103));
        CalculateButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(255, 255, 255));
        CalculateButton.setText("Calculate");
        CalculateButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CalculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(47, 70, 103));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButtonMouseClicked(evt);
            }
        });

        ShowGraph.setBackground(new java.awt.Color(47, 70, 103));
        ShowGraph.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShowGraph.setForeground(new java.awt.Color(255, 255, 255));
        ShowGraph.setText("Show Graph");
        ShowGraph.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ShowGraph.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowGraphActionPerformed(evt);
            }
        });

        MonthlyLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MonthlyLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MonthlyLabel1.setText("Monthly Groceries:");

        MedicalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicalLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MedicalLabel1.setText("Consumers Energy:");

        Consumer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MedicalLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicalLabel2.setForeground(new java.awt.Color(255, 255, 255));
        MedicalLabel2.setText("Other Expenses:");

        OtherExpenses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MedicalLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicalLabel3.setForeground(new java.awt.Color(255, 255, 255));
        MedicalLabel3.setText("Medical Expenses:");

        Medical.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        MedicalLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MedicalLabel4.setForeground(new java.awt.Color(255, 255, 255));
        MedicalLabel4.setText("Monthly Taxes:");

        Tax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MonthlyLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MonthlyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Groceries, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(MedicalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TaxLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entertainment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Electricity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(ShowGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CalculateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClearButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MedicalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OtherExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MedicalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Medical, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MedicalLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(MedicalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Consumer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Groceries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonthlyLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MonthlyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Gas)))
                    .addComponent(ShowGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entertainment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Electricity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Consumer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OtherExpenses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Medical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicalLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tax))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateButton)
                    .addComponent(ClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
      
       

try{
            tmp.setTax(Double.parseDouble(Tax.getText()));
            tmp.setConsumersEnergy(Double.parseDouble(Consumer.getText()));
            tmp.setElectricity(Double.parseDouble(Electricity.getText()));
            tmp.setEntertainment(Double.parseDouble(Entertainment.getText()));
            tmp.setGas(Double.parseDouble(Gas.getText()));
            tmp.setGroceries(Double.parseDouble(Gas.getText()));
            tmp.setMedicalExpense(Double.parseDouble(Medical.getText()));
            tmp.setOtherMonthlyExpenses(Double.parseDouble(OtherExpenses.getText()));
            
            double x = tmp.getTotalExpense();
            TotalTxt.setText(String.valueOf(fmt.format(x)));
            Entertainment.setText(String.valueOf(fmt.format(tmp.getEntertainment())));
            Electricity.setText(String.valueOf(fmt.format(tmp.getElectricity())));
            Groceries.setText(String.valueOf(fmt.format(tmp.getGroceries())));
            Gas.setText(String.valueOf(fmt.format(tmp.getGas())));
            Medical.setText(String.valueOf(fmt.format(tmp.getMedicalExpense())));
            Consumer.setText(String.valueOf(fmt.format(tmp.getConsumersEnergy())));
            Tax.setText(String.valueOf(fmt.format(tmp.getTax())));
            OtherExpenses.setText(String.valueOf(fmt.format(tmp.getotherMonthlyExpenses())));
            
} catch(Exception e){
    JOptionPane.showMessageDialog(null, "Error Occured: " + e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
}
            
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void EntertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntertainmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntertainmentActionPerformed

    private void ClearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseClicked
       
        
        Entertainment.setText("");
        Electricity.setText("");
        Groceries.setText("");
        Gas.setText("");
        TotalTxt.setText("");
        Medical.setText("");
        Consumer.setText("");
        Tax.setText("");
        OtherExpenses.setText("");
    }//GEN-LAST:event_ClearButtonMouseClicked

    private void GroceriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroceriesActionPerformed
        
    }//GEN-LAST:event_GroceriesActionPerformed

    private void ShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowGraphActionPerformed
         

           
try{
            DefaultPieDataset dcd = new DefaultPieDataset();
            
            double xEnt = tmp.getEntertainment()/tmp.getTotalExpense();
            double xElec = tmp.getElectricity()/tmp.getTotalExpense();
            double xGroc = tmp.getGroceries()/tmp.getTotalExpense();
            double xGas = tmp.getGas()/tmp.getTotalExpense();
            double xMed = tmp.getMedicalExpense()/tmp.getTotalExpense();
            double xCons = tmp.getConsumersEnergy()/tmp.getTotalExpense();
            double xTax = tmp.getTax()/tmp.getTotalExpense();
            double xOth = tmp.getotherMonthlyExpenses()/tmp.getTotalExpense();
            
            dcd.setValue("Entertainment " + per.format(xEnt), tmp.getEntertainment());
            dcd.setValue("Electricity " + per.format(xElec), tmp.getElectricity());
            dcd.setValue("Groceries " + per.format(xGroc), tmp.getGroceries());
            dcd.setValue("Gas " + per.format(xGas), tmp.getGas());
            dcd.setValue("Medical " + per.format(xMed), tmp.getMedicalExpense());
            dcd.setValue("Consumers Energy " + per.format(xCons), tmp.getConsumersEnergy());
            dcd.setValue("Tax " + per.format(xTax), tmp.getTax());
            dcd.setValue("Other Expenses " + per.format(xOth), tmp.getotherMonthlyExpenses());
                    
            JFreeChart j = ChartFactory.createPieChart("Expenses", dcd, true, true, false);


            ChartFrame frame = new ChartFrame("Expenses",j);
            frame.setVisible(true);
            frame.setSize(600,800);

       
        
            
            
} catch (Exception e){
    JOptionPane.showMessageDialog(null, "Error Occured: " + e.getMessage(), "Error", JOptionPane.INFORMATION_MESSAGE);
}
                    
                      
    }//GEN-LAST:event_ShowGraphActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField Consumer;
    private javax.swing.JTextField Electricity;
    private javax.swing.JTextField Entertainment;
    private javax.swing.JTextField Gas;
    private javax.swing.JTextField Groceries;
    private javax.swing.JTextField Medical;
    private javax.swing.JLabel MedicalLabel;
    private javax.swing.JLabel MedicalLabel1;
    private javax.swing.JLabel MedicalLabel2;
    private javax.swing.JLabel MedicalLabel3;
    private javax.swing.JLabel MedicalLabel4;
    private javax.swing.JLabel MonthlyLabel;
    private javax.swing.JLabel MonthlyLabel1;
    private javax.swing.JTextField OtherExpenses;
    private javax.swing.JButton ShowGraph;
    private javax.swing.JTextField Tax;
    private javax.swing.JLabel TaxLabel;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}